import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({ standalone: true, imports: [RouterLink], template: `
  <section class="hero-section page-hero"><div class="hero-overlay"></div><div class="container hero-content"><p class="eyebrow light"><span></span> Servicio rápido, seguro y confiable</p><h1>Movemos lo que<br /><em>importa.</em></h1><p class="hero-description">Conectamos personas, ciudades y oportunidades con la fuerza de una flota preparada para llegar más lejos.</p><div class="hero-stats"><div><strong>+15</strong><span>años de experiencia</span></div><div><strong>24/7</strong><span>atención y soporte</span></div><div><strong>100%</strong><span>compromiso peruano</span></div></div></div></section>
  <section class="section-space home-intro"><div class="container split-heading"><div><p class="eyebrow">Una ruta con propósito</p><h2>La confianza también<br /><em>se transporta.</em></h2></div><div><p class="body-copy">Transportes 41 S.A.C. conecta personas, ciudades y oportunidades con responsabilidad, puntualidad y un profundo respeto por quienes confían en nosotros.</p><a class="text-link" routerLink="/nosotros">Conoce nuestra empresa <span>→</span></a></div></div></section>
` })
export class HomePage {}

@Component({ standalone: true, template: `
  <section class="inner-hero"><div class="container"><p class="eyebrow">01 / Quiénes somos</p><h1>La confianza también<br /><em>se transporta.</em></h1><p>Una empresa peruana que convierte cada recorrido en una experiencia segura y responsable.</p></div></section>
  <section class="section-space"><div class="container intro-grid"><div class="section-label"><span>01</span><i></i><small>Sobre 41 S.A.C.</small></div><div class="intro-copy"><p class="eyebrow">Una ruta con propósito</p><h2>Personas que mueven<br /><em>personas.</em></h2><p>Transportes 41 S.A.C. es una empresa peruana dedicada al transporte de personas y mercancías. Trabajamos para conectar ciudades con un servicio puntual, seguro y cercano.</p></div><div class="intro-note"><div class="quote-mark">“</div><p>Hacemos del camino un lugar más seguro para todos.</p><span>— Equipo 41 S.A.C.</span></div></div><div class="container about-details"><div class="about-card"><span class="about-index">01</span><h3>Misión</h3><p>Brindar soluciones de transporte confiables, cuidando a cada pasajero, carga y colaborador durante todo el recorrido.</p></div><div class="about-card"><span class="about-index">02</span><h3>Visión</h3><p>Ser una empresa referente en movilidad responsable y eficiente, reconocida por la calidad de nuestro servicio.</p></div><div class="about-card"><span class="about-index">03</span><h3>Principios</h3><p>Seguridad, puntualidad, respeto y mejora continua en cada decisión que tomamos.</p></div></div></section>
  <section class="route-section section-space"><div class="container"><div class="section-heading"><div><p class="eyebrow">Nuestra cobertura</p><h2>Una ruta que<br /><em>conecta.</em></h2></div><p class="heading-support">Mapa GPS de referencia para visualizar nuestra cobertura. Puedes reemplazar las coordenadas por tus rutas reales.</p></div><div class="gps-map"><iframe title="Mapa GPS de rutas de Transportes 41 S.A.C." src="https://www.openstreetmap.org/export/embed.html?bbox=-77.35%2C-12.35%2C-76.75%2C-11.65&amp;layer=mapnik&amp;marker=-12.0464%2C-77.0428"></iframe></div><a class="map-link" href="https://www.openstreetmap.org/?mlat=-12.0464&amp;mlon=-77.0428#map=10/-12.0464/-77.0428" target="_blank" rel="noopener">Abrir mapa GPS completo <span>↗</span></a></div></section>
` })
export class AboutPage {}

@Component({ standalone: true, imports: [RouterLink], template: `
  <section class="inner-hero services-hero"><div class="container"><p class="eyebrow">02 / Servicios</p><h1>Transporte pensado<br /><em>para avanzar.</em></h1><p>Soluciones claras para mover personas, mercancías y operaciones con confianza.</p></div></section>
  <section class="service-intro section-space"><div class="container service-intro-grid"><div><p class="eyebrow">Lo que hacemos</p><h2>Cada recorrido<br /><em>tiene un propósito.</em></h2></div><p class="body-copy">Ponemos nuestra experiencia, equipo y capacidad operativa al servicio de cada cliente. Elige la solución que necesitas y construyamos juntos una ruta más eficiente.</p></div></section>
  <section class="services-section services-catalog section-space"><div class="container"><div class="service-grid service-grid-large"><article class="service-card service-card-dark"><span class="card-number">01 / CIUDAD</span><div class="service-icon">◌</div><h3>Transporte urbano</h3><p>Movilidad eficiente y cercana para conectar cada punto de la ciudad.</p><a routerLink="/contacto">Solicitar servicio <span>↗</span></a></article><article class="service-card service-card-red"><span class="card-number">02 / CARGA</span><div class="service-icon">⌁</div><h3>Transporte de carga</h3><p>Trasladamos tus productos con cuidado, trazabilidad y puntualidad.</p><a routerLink="/contacto">Solicitar servicio <span>↗</span></a></article><article class="service-card service-card-light"><span class="card-number">03 / OPERACIÓN</span><div class="service-icon">✦</div><h3>Gestión de flota</h3><p>Operación y mantenimiento para que cada unidad esté lista.</p><a routerLink="/contacto">Solicitar servicio <span>↗</span></a></article></div></div></section>
  <section class="service-process section-space"><div class="container"><div class="section-heading"><div><p class="eyebrow">Así trabajamos</p><h2>Simple para ti.<br /><em>Preciso para nosotros.</em></h2></div><p class="heading-support">Nos ocupamos de la operación para que tú puedas concentrarte en lo que sigue.</p></div><div class="process-grid"><div><span>01</span><h3>Escuchamos</h3><p>Entendemos tu necesidad y el destino de tu operación.</p></div><div><span>02</span><h3>Planificamos</h3><p>Diseñamos la ruta, los recursos y los tiempos adecuados.</p></div><div><span>03</span><h3>Acompañamos</h3><p>Damos seguimiento hasta que todo llega bien.</p></div></div></div></section>
` })
export class ServicesPage {}

@Component({ standalone: true, template: `
  <section class="inner-hero"><div class="container"><p class="eyebrow">03 / Nuestra flota</p><h1>Una flota que<br /><em>responde.</em></h1><p>Unidades preparadas, mantenimiento preventivo y seguimiento permanente.</p></div></section>
  <section class="fleet-section fleet-page"><div class="container fleet-grid"><div class="fleet-visual"><div class="circle-badge"><span>41</span><small>S.A.C.</small></div><div class="fleet-line"></div><p>Listos para<br /><strong>seguir avanzando.</strong></p></div><div class="fleet-copy"><p class="eyebrow light">Nuestra operación</p><h2>Seguridad en<br /><em>cada kilómetro.</em></h2><p>Contamos con unidades modernas, revisadas y preparadas para operar con altos estándares de calidad.</p><div class="fleet-list"><div><strong>01</strong><span>Mantenimiento preventivo</span></div><div><strong>02</strong><span>Conductores capacitados</span></div><div><strong>03</strong><span>Monitoreo permanente</span></div></div></div></div></section>
` })
export class FleetPage {}

@Component({ standalone: true, template: `
  <section class="inner-hero"><div class="container"><p class="eyebrow">04 / Seguridad</p><h1>Más que llegar,<br /><em>llegar bien.</em></h1><p>La seguridad es una práctica diaria que guía cada recorrido.</p></div></section>
  <section class="section-space"><div class="container values-grid"><div><p class="eyebrow">Nuestro compromiso</p><h2>Un servicio<br /><em>con propósito.</em></h2></div><div class="values-list"><div><span>01</span><div><h3>Seguridad primero</h3><p>Cuidamos a nuestros pasajeros, colaboradores y comunidades en cada recorrido.</p></div></div><div><span>02</span><div><h3>Servicio humano</h3><p>Escuchamos, acompañamos y resolvemos con respeto y cercanía.</p></div></div><div><span>03</span><div><h3>Mirada al futuro</h3><p>Buscamos una movilidad más ordenada, responsable y sostenible.</p></div></div></div></div></section>
` })
export class SafetyPage {}

@Component({ standalone: true, template: `
  <section class="inner-hero"><div class="container"><p class="eyebrow">05 / Contáctanos</p><h1>Tu próximo destino<br /><em>empieza aquí.</em></h1><p>Cuéntanos qué necesitas y nuestro equipo se pondrá en contacto contigo.</p></div></section>
  <section class="contact-section contact-page"><div class="container contact-grid"><div><p class="eyebrow light">Hablemos</p><h2>Estamos listos<br /><em>para ayudarte.</em></h2><p>Atendemos consultas comerciales, solicitudes de transporte y alianzas.</p></div><form class="contact-form" (submit)="$event.preventDefault()"><label>Nombre completo<input type="text" placeholder="Escribe tu nombre" /></label><label>Correo electrónico<input type="email" placeholder="tu@correo.com" /></label><label>¿Cómo podemos ayudarte?<textarea rows="3" placeholder="Cuéntanos brevemente"></textarea></label><button class="button button-primary" type="submit">Enviar mensaje <span>↗</span></button></form></div></section>
` })
export class ContactPage {}

@Component({ standalone: true, template: `
  <section class="inner-hero care-hero"><div class="container"><p class="eyebrow">Atención al cliente</p><h1>Estamos contigo<br /><em>en cada recorrido.</em></h1><p>Resuelve tus dudas, consulta el estado de tu servicio o cuéntanos cómo podemos ayudarte.</p></div></section>
  <section class="care-section section-space"><div class="container"><div class="section-heading"><div><p class="eyebrow">Centro de ayuda</p><h2>¿En qué podemos<br /><em>ayudarte?</em></h2></div><p class="heading-support">Encuentra una respuesta rápida o déjanos tus datos y nuestro equipo te atenderá.</p></div><div class="help-grid"><article><span>01</span><h3>Consultar un servicio</h3><p>¿Necesitas información sobre un viaje, entrega o atención en curso?</p><a href="#ayuda">Hacer consulta <b>↗</b></a></article><article><span>02</span><h3>Seguimiento</h3><p>Indícanos tu código de servicio para revisar el estado de tu solicitud.</p><a href="#ayuda">Ver seguimiento <b>↗</b></a></article><article><span>03</span><h3>Preguntas frecuentes</h3><p>Conoce respuestas sobre horarios, reservas, carga y canales de atención.</p><a href="#ayuda">Leer respuestas <b>↗</b></a></article></div></div></section>
  <section id="ayuda" class="care-form-section"><div class="container care-form-grid"><div><p class="eyebrow light">Atención 41 S.A.C.</p><h2>Cuéntanos<br /><em>qué necesitas.</em></h2><p>Te responderemos con la información adecuada para tu caso.</p></div><form class="contact-form" (submit)="$event.preventDefault()"><label>Motivo de consulta<select><option>Selecciona una opción</option><option>Consulta sobre servicio</option><option>Seguimiento</option><option>Información de horarios</option><option>Otro</option></select></label><label>Nombre completo<input type="text" placeholder="Escribe tu nombre" /></label><label>Correo electrónico<input type="email" placeholder="tu@correo.com" /></label><label>Mensaje<textarea rows="3" placeholder="Escribe tu consulta"></textarea></label><button class="button button-primary" type="submit">Enviar consulta <span>↗</span></button></form></div></section>
` })
export class CustomerCarePage {}

@Component({ standalone: true, template: `
  <section class="inner-hero claims-hero"><div class="container"><p class="eyebrow">Libro de reclamaciones</p><h1>Tu experiencia<br /><em>nos ayuda a mejorar.</em></h1><p>Registra aquí una queja o reclamo relacionado con nuestros servicios.</p></div></section>
  <section class="claims-section section-space"><div class="container claims-layout"><div class="claims-aside"><p class="eyebrow">Antes de empezar</p><h2>Queremos<br /><em>escucharte.</em></h2><p>Completa los datos con claridad. Revisaremos tu solicitud y te responderemos dentro del plazo establecido.</p><div class="claims-note"><strong>Importante</strong><span>Este formulario es una guía visual. Para recibir reclamos oficialmente, debes conectarlo a tu correo o sistema de atención.</span></div></div><form class="claims-form" (submit)="$event.preventDefault()"><div class="form-heading"><span>01</span><h3>Datos del consumidor</h3></div><div class="form-row"><label>Nombre completo<input type="text" placeholder="Escribe tu nombre" /></label><label>DNI / RUC<input type="text" placeholder="Número de documento" /></label></div><div class="form-row"><label>Correo electrónico<input type="email" placeholder="tu@correo.com" /></label><label>Teléfono<input type="tel" placeholder="Número de contacto" /></label></div><div class="form-heading"><span>02</span><h3>Detalle de la solicitud</h3></div><label>Tipo de solicitud<select><option>Selecciona una opción</option><option>Queja</option><option>Reclamo</option><option>Sugerencia</option></select></label><label>Fecha del servicio<input type="date" /></label><label>Cuéntanos qué ocurrió<textarea rows="5" placeholder="Describe los hechos con el mayor detalle posible"></textarea></label><label>¿Qué solución esperas?<textarea rows="3" placeholder="Escribe tu solicitud"></textarea></label><label class="check-label"><input type="checkbox" /> Confirmo que la información brindada es verdadera.</label><button class="button button-primary" type="submit">Enviar solicitud <span>↗</span></button></form></div></section>
` })
export class ClaimsPage {}